version: "3.7"

services:
  faraday-server-db:
    image: postgres:9.4
    restart: unless-stopped
    volumes:
      - "faraday-server-db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=faraday
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=faraday

  faraday-server-app:
    build:
      context: ./images/faraday-server
    image: pbehnke/faraday-server:latest
    restart: unless-stopped
    volumes:
      - "faraday-server-app-data:/root/.faraday"
    environment:
      - POSTGRES_HOST=faraday-server-db
      - POSTGRES_USER=faraday
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=faraday
      - FARADAY_SUPERUSER_NAME=Admin
      - FARADAY_SUPERUSER_EMAIL=admin@example.com
      - FARADAY_SUPERUSER_PASSWORD=changeme
    ports:
      - "5985:5985"
      - "9000:9000"

volumes:
  faraday-server-db-data:
  faraday-server-app-data:
